### ISSUE TITLE
GCP - add cloud function and scheduler to re-scrape events

### ISSUE THREAD

**Issue by TheFatPanda97** [GDSCUTM-CommunityProjects/ActNow#105]
**Description**
Currently, we do not have an automated way to re-scrape the events we have. So, we will create another cloud functional and scheduler to periodically re-scrape the top 10 oldest city collections.

**TODO**
- [x] extract the current scraper logic into a non-cloud, helper function
- [x] create new cloud function that grabs the top 10 oldest city collection
- [ ] add collection to call this function once a day

**Additional context**
N/A
