### ISSUE TITLE
Application - write tests for search_widget.dart

### ISSUE THREAD

**Issue by TheFatPanda97** [GDSCUTM-CommunityProjects/ActNow#129]
**Description**
For this ticket, we will be writing some tests for search_widget.dart

**TODO**
- [ ] test for on change handler
- [ ] test for hint text 
- [ ] test for input text

**Additional context**
N/A
