### ISSUE TITLE
Application - clean up profile page

### ISSUE THREAD

**Issue by TheFatPanda97** [GDSCUTM-CommunityProjects/ActNow#134]
**Description**
Currently, there are several unused items on the profile page, in this issue, we will populate it with actual functionality. 

**TODO**
- [x] link `How to use ActNow` to our docs page
- [x] link terms of service to our GitHub license page
- [x] remove notifications setting

**Additional context**
N/A
