### ISSUE TITLE
Application - create saved events page

### ISSUE THREAD

**Issue by TheFatPanda97** [GDSCUTM-CommunityProjects/ActNow#95]
**Description**
For this issue, we will be creating the saved events page. The primary objective is to allow the users to see events that they have saved or joined.
![Main App (Saved 1)](https://user-images.githubusercontent.com/36747253/139961167-f58bc551-70b5-4758-bb6b-26fc6f1ae0b5.png)

**TODO**
- [x] implement search bar for both the saved events page and well the normal events page
- [x] implement filter bar with options of
  - [x] saved
  - [x] joined
  - [x] created
- [x] display saved, joined, and created events on saved events page

**Additional context**
Issue #96  will have to be completed first

**Comment by TheFatPanda97** [comment]
Blocked by #96
