### ISSUE TITLE
Application - implement user location on map

### ISSUE THREAD

**Issue by TheFatPanda97** [GDSCUTM-CommunityProjects/ActNow#97]
**Description**
For this issue, we will be implementing the ability for users to share their location on the map. By default, we will have this option turned off, by a user should be able to toggle this functionality in the settings page.

**TODO**
- [ ] ability for users to toggle this option on and off in the settings page (off by default)
- [ ] when a user turns off this option, their location should be completely deleted on firestore
- [ ] periodically update their location in firestore (every 5 minutes)
- [ ] display user location the maps as blue pins

**Additional context**
N/A
